version: '3.7'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DISCORD_WEBHOOK=https://discordapp.com/api/webhooks/1226184050423758988/7rqdlvqtOQmtB7dWIhzluv88yPltYLuqOPe9TRILONr9KwNLHL8nHMLTTsULAlsLPk8C
    command: ["python", "main.py", "/app/data/example.config.yml"]
    volumes:
      - /home/hakedev/Code/hubble:/app/data # config.yml file for cosmos
      - /var/run/docker.sock:/var/run/docker.sock # Need this to run docker commands